### ISSUE TITLE
Drivers Sometimes don't load after reboot

### ISSUE THREAD

**Issue by frank6311** [colin-campbell/firestudio-catalina#18]
This may not even be an issue with your Fix.  May be a macOS issue but after a reboot the drivers don't load and so the Presonus UI seems to crash.  After second restart the drivers appear to be fine and everything works as expected.  Looked for a solution but could not find an answer as to why it happens.  As  I said it may be a macOS issue anyway.
thanks for the great work btw.

**Comment by colin-campbell** [comment]
Which OS version are you using? If the sync light is flashing and not steady on the hardware, then the drivers have not loaded.

**Comment by frank6311** [comment]
Hey thanks for the reply.  I am on macos Monterey.  The light stays solid.
But after a restart there is a message stating that there is a problem with
the drivers.  Even then the light stays solid but the interface doesn't
work.  If I restart a second time everything works fine.  I am using the
Fire studio Mobile.
Thanks for your great work btw!  The Mobile wouldn't work at all prior to
your fix.

**Comment by colin-campbell** [comment]
The only message I usually get from time to time, is "This driver may be incompatible with a future version of MacOS" after an install. Is there a specific message?
