### ISSUE TITLE
How to clean uninstall the driver ?

### ISSUE THREAD

**Issue by Arthurdhaeyer** [colin-campbell/firestudio-catalina#21]
Hi Colin, your driver is amazing, I used it for a year with both a Firestudio Mobile and Project : perfect !
But two weeks ago, overnight, I couldn't use my devices anymore, for no reason !
I tried may things, and my cards are ok (tested on another computer).

I deleted the firmware downloaded a year ago and installed the somewhat new version, it did not solved my problem.
Maybe I deleted it wrong ? How to clean uninstall the program ? I don't see any Uninstall button or file...
thank you very much Colin !

I also sent you an email with more details at colin.campbell@d********group.com

**Comment by colin-campbell** [comment]
@Arthurdhaeyer I have mailed you back. Please continue the discussion here though.

**Comment by Arthurdhaeyer** [comment]
Hi, thanks for you answer.
I did what you told me : not try to uninstall, just run the installer again then double check in privacy and security settings that the driver is allowed to load. Which I did, then restart the computer, and still my cards blink red/blue and are not usable. Damn...
The only place I can see the soundcard is when I do a System Report and go to the Firewire tab, which should mean that my firewire port is not dead, right ?
thanks a lot !

**Comment by Arthurdhaeyer** [comment]
sorry I didn't mean to close the discussion, just clicked randomly on the button

**Comment by colin-campbell** [comment]
@Arthurdhaeyer Your fw port should be ok.

You can check if the driver is loading by opening a terminal and issuing the command:
`kextstat | grep PaeFireStudio` 

You should see output similar to this (not identical) if the driver is loaded.
`  180    0 0xffffff7f962a4000 0x17ffc    0x17ffc    tc.tctechnologies.driver.PaeFireStudio (4.2.1 46437) 9D76C25B-A48C-34EF-9E49-B72392F3199C <179 178 7 6 3 1>`

**Comment by Arthurdhaeyer** [comment]
Hi, thanks for your answer,
when I do `kextstat | grep PaeFireStudio` : nothing happens
when I do `kextstat` : I see 179 lines and no mention of PaeFireStudio...

strange ?

![Capture d’écran 2024-01-24 à 13 33 59](https://github.com/colin-campbell/firestudio-catalina/assets/156323613/7ca13d8e-4d27-4ed7-a2ef-e61e266f1f9d)

Thank you very much for your attention Colin !

**Comment by Arthurdhaeyer** [comment]
Hi Colin, do you have any ideas what I could do next ? I am stuck...
Thanks a lot for your help ! :)

**Comment by Arthurdhaeyer** [comment]
Could you tell me how to properly uninstall the driver, maybe there is a command to type or smth to delete in Library, I don't know. I feel stuck, music is my work the problem is I can't afford a new macbook pro and it feels crazy to buy new soundcards as those are working perfectly fine... thanks again for your help, sorry to disturb you but you are the only person I know who can understand a word of this !
best regards !

**Comment by Arthurdhaeyer** [comment]
WUUP ! I managed to solve my problem !
![Capture d’écran 2024-02-23 à 12 14 47](https://github.com/colin-campbell/firestudio-catalina/assets/156323613/bc23d811-abb8-4cd5-8c1e-c43f6ec0353c)
What i did was simple, I deleted the app simply by drag and drop to the bin, empty the bin, turn of the computer, do SMC and PRAM reset, turn on the mac, download and install your firmware, reboot the mac, then it was working like it did !!
I feel so relieved !
