### ISSUE TITLE
PreSonus FireStudio Mobile: works like a charm - CONFIRMED :)

### ISSUE THREAD

**Issue by till213** [colin-campbell/firestudio-catalina#9]
This is not an issue, but rather to let people know that my PreSonus FireStudio Mobile - connected via FireWire to an OWC Thunderbolt 3 Dock (the early variant that still had a FireWire connector), connected to an iMac 27" 2020 - works like a charm! As just tested on latest (at the time of this writing) macOS Big Sur.

Some quick tests that I did:

- Universal Control detects the device and shows the mixer
- A quick headphone fader test properly set the headphone volume
- MIDI events from a connected keyboard are received just fine (tested with PreSonus Studio One 4, which also detects the FireStudio Mobile device)
- And of course the macOS audio mixer detects the device just fine as well: system audio works

**Comment by colin-campbell** [comment]
Will close this - as tested up to Ventura 13.1
